application: chromeappsnow
version: 2 
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /(.*\.css)
  mime_type: text/css
  static_files: static/\1
  upload: static/(.*\.css)

- url: /(.*\.html)
  mime_type: text/html
  static_files: static/\1
  upload: static/(.*\.html)

- url: /(.*\.json)
  mime_type: text/javascript
  static_files: static/\1
  upload: static/(.*\.json)

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: static/\1
  upload: static/(.*\.js)

- url: /(.*\.(gif|ico|jpeg|jpg|png))
  static_files: static/\1
  upload: static/(.*\.(gif|ico|jpeg|jpg|png))

# site root
- url: /
  static_files: static/index.html
  upload: static/index.html
